.TH SW 1 sw\-VERSION
.SH NAME
sw \- simple wallet
.SH SYNOPSIS
.B sw
.RB [ \-v ]\ [ \-defiltx \ <arg>]\  [<date\ [time]\>\ <amount>\ <note>]
.SH DESCRIPTION
sw is a wallet management tool which features a simple yet powerful interface
to keep track of your money movements. By default (if no -l, -f or -t is
specified) last 25 movements are shown.

To add a movement run sw with the following arguments:
.TP
.B date time
a string for the date in the format dd/mm/yyyy optionally followed by a time
(hh:mm). If no time is specified 00:00 is assumed. The word "now" can be used
to in place of the current date and time.
.TP
.B amount
floating point value which can be positive (incomes) or negative (expenses)
.TP
.B note
An arbitrary string which identify the movement
.TP
Example: sw "14/08/2024 14:52" -90.52 "Food and drink for Ferragosto"
.SH OPTIONS
.TP
.B \-v
prints version information to standard output, then exits.
.TP
.B \-d\ <id>
remove the specified movement, then exits.
.TP
.B \-e\ <text>
show only movements that match the given string (case insensitive). May be
specified multiple times.
.TP
.B \-f\ <date\ [time]>
show only movements corresponding to or subsequent to the given date (and
optional time) string. See DESCRIPTION for informations on date and time
formats.
.TP
.B \-i\ <file>
use the given file as movements database.
.TP
.B \-l\ <limit>
limit the number of movements in the listing. If zero is specified then assume
a value of INT_MAX (show all movements).
.TP
.B \-t\ <date\ [time]>
show only movements corresponding to or prior to the given date (and optional
time) string. See DESCRIPTION for informations on date and time formats.
.TP
.B \-x\ <text>
exclude all movements that include the given string (case insensitive). May be
specified multiple times.
.SH NOTES
Custom formats for dates will be supported in future version of sw.
