.TH SW 1 sw\-VERSION
.SH NAME
sw \- simple wallet
.SH SYNOPSIS
.B sw
.RB [ \-v ]\ [ \-d \ <id>]\ [ \-i \ <file>]\ [ \-l \ <limit>]\ [<date>\ <amount>\ <note>]
.SH DESCRIPTION
sw is a simple wallet management tool which features a simple yet powerful
interface to keep track of your money movements.
.SH OPTIONS
.TP
.B \-v
prints version information to standard output, then exits.
.TP
.B \-d\ <id>
remove the specified movement, then exits.
.TP
.B \-f\ <file>
use the given file as movements database.
.TP
.B \-l\ <limit>
limit the number of movements in the listing.
